module.exports = {
  mySidebar: [
    'introduction',
    {
      type: 'autogenerated',
      dirName: 'architecture',
    },
    {
      type: 'autogenerated',
      dirName: 'quick-start',
    },
    {
    type: 'category',
    label: 'Installation',
    link: {type: 'doc', id: 'installation/installation',},
    items:[
      {
        type: 'category',
        label: 'Installation Requirements',
        link: {type: 'doc', id: 'installation/installation-requirements/installation-requirements',},
        items: ['installation/installation-requirements/resource-profiling/resource-profiling'],
      },
      {
        type: 'category',
        label: 'Installation Options',
        link: {type: 'doc', id: 'installation/install-options/install-options',},
        items: [
          {
            type: 'autogenerated',
            dirName: 'installation/install-options/server-config',
          },
          {
            type: 'autogenerated',
            dirName: 'installation/install-options/agent-config',
          },
          {
            type: 'autogenerated',
            dirName: 'installation/install-options/how-to-flags',
          },
        ],
      },
      'installation/network-options/network-options',
      'installation/ha/ha',
      'installation/ha-embedded/ha-embedded',
      'installation/datastore/datastore',
      'installation/private-registry/private-registry',
      'installation/airgap/airgap',
      'installation/disable-flags/disable-flags',
      'installation/kube-dashboard/kube-dashboard',
      'installation/uninstall/uninstall',
    ],
  },
    {
      type: 'autogenerated',
      dirName: 'cluster-access',
    },
    {
      type: 'category',
      label: 'Upgrades',
      link: {type: 'doc', id: 'upgrades/upgrades',},
      items:[
          {
            type: 'autogenerated',
            dirName: 'upgrades/killall',
          },
          {
            type: 'autogenerated',
            dirName: 'upgrades/basic',
          },
          {
            type: 'autogenerated',
            dirName: 'upgrades/automated',
          },
        ],
    },

    {
      type: 'autogenerated',
      dirName: 'backup-restore',
    },
    {
      type: 'autogenerated',
      dirName: 'storage',
    },
    {
      type: 'autogenerated',
      dirName: 'networking',
    },
    {
      type: 'autogenerated',
      dirName: 'helm',
    },
    {
      type: 'autogenerated',
      dirName: 'advanced',
    },
    {
      type: 'autogenerated',
      dirName: 'faq',
    },
    {
      type: 'autogenerated',
      dirName: 'known-issues',
    },
    {
      type: 'category',
      label: 'Security',
      link: {type: 'doc', id: 'security/security'},
      items:[
        {
          type: 'autogenerated',
          dirName: 'security/secrets_encryption',
        },
        {
          type: 'autogenerated',
          dirName: 'security/hardening_guide',
        },
        {
          type: 'autogenerated',
          dirName: 'security/self_assessment',
        },
      ],
    },
  ],
};