module.exports = {
  mySidebar: [
    'introduction',
    {
      type: 'autogenerated',
      dirName: 'architecture',
    },
    {
      type: 'autogenerated',
      dirName: 'quick-start',
    },
    {
      type: 'category',
      label: 'Installation',
      link: { type: 'doc', id: 'installation/installation',},
      items:[
        'installation/requirements',
        'installation/configuration',
        'installation/network-options',
        {
          type: 'category',
          label: 'Cluster Datastore Options',
          link: {type: 'doc', id: 'installation/datastore',},
          items: [
            'installation/ha-embedded',
            'installation/ha',
          ],
        },
        'installation/private-registry',
        'installation/airgap',
        'installation/disable-flags',
        'installation/addons',
        'installation/kube-dashboard',
        'installation/uninstall',
      ],
    },
    {
      type: 'autogenerated',
      dirName: 'cluster-access',
    },
    {
      type: 'category',
      label: 'Upgrades',
      link: {type: 'doc', id: 'upgrades/upgrades',},
      items:[
        'upgrades/killall',
        'upgrades/manual',
        'upgrades/automated',
      ],
    },
    {
      type: 'autogenerated',
      dirName: 'backup-restore',
    },
    {
      type: 'autogenerated',
      dirName: 'storage',
    },
    {
      type: 'autogenerated',
      dirName: 'networking',
    },
    {
      type: 'autogenerated',
      dirName: 'helm',
    },
    {
      type: 'autogenerated',
      dirName: 'advanced',
    },
    {
      type: 'autogenerated',
      dirName: 'faq',
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        'reference/server-config',
        'reference/agent-config',
        'reference/env-variables',
        `reference/binary-tools`,
        'reference/resource-profiling',
      ],
    },
    {
      type: 'autogenerated',
      dirName: 'known-issues',
    },
    {
      type: 'category',
      label: 'Security',
      link: {type: 'doc', id: 'security/security'},
      items:[
        'security/secrets-encryption',
        'security/hardening-guide',
        'security/self-assessment',
      ],
    },
  ],
};
